# Generated by Django 4.1.5 on 2023-01-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_mun', models.CharField(blank=True, default=None, max_length=2, null=True)),
                ('nom_mun_corto', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('nom_mun_largo', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('presidente', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('poblacion', models.IntegerField(blank=True, default=None, null=True)),
                ('localidades', models.IntegerField(blank=True, default=None, null=True)),
                ('superficie', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('prg_gob', models.TextField(blank=True, default=None, null=True)),
                ('prg_gob2', models.TextField(blank=True, default=None, null=True)),
                ('panorama_sociodem', models.TextField(blank=True, default=None, null=True)),
                ('pmd', models.TextField(blank=True, default=None, null=True)),
                ('nom_pmd', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
    ]
