# Generated by Django 4.1.5 on 2023-01-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infomun', '0002_alter_municipio_cve_mun'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('url', models.TextField(blank=True, default=None, null=True)),
                ('seccion', models.IntegerField(blank=True, default=None, null=True)),
                ('posicion', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
