# Generated by Django 4.1.5 on 2023-01-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infomun', '0003_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='etiqueta',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
