# Generated by Django 4.1.5 on 2023-01-25 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infomun', '0004_alter_documento_etiqueta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['seccion', 'posicion']},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'ordering': ['cve_mun']},
        ),
        migrations.AddField(
            model_name='documento',
            name='cve_mun',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, to='infomun.municipio'),
            preserve_default=False,
        ),
    ]
