# Generated by Django 4.1.5 on 2023-01-25 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infomun', '0005_alter_documento_options_alter_municipio_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='cve_mun',
        ),
    ]
