# Generated by Django 4.1.5 on 2023-01-25 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infomun', '0006_remove_documento_cve_mun'),
    ]

    operations = [
        migrations.RenameModel("Documento", "Documento_comun")
    ]
