# Generated by Django 4.1.5 on 2023-01-25 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infomun', '0008_documento_municipio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.TextField(blank=True, default=None, null=True)),
                ('url', models.TextField(blank=True, default=None, null=True)),
                ('seccion', models.IntegerField(blank=True, default=None, null=True)),
                ('posicion', models.IntegerField(blank=True, default=None, null=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infomun.municipio')),
            ],
            options={
                'ordering': ['seccion', 'posicion'],
            },
        ),
        migrations.DeleteModel(
            name='Documento_comun',
        ),
        migrations.DeleteModel(
            name='Documento_municipio',
        ),
    ]
