# Generated by Django 4.1.5 on 2023-01-26 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infomun', '0011_remove_municipio_nom_pmd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipio',
            name='escudo',
        ),
    ]
