# Generated by Django 4.1.5 on 2023-01-26 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infomun', '0013_municipio_escudo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipio',
            name='escudo',
        ),
    ]
