# Generated by Django 4.1.5 on 2023-01-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infomun', '0015_municipio_escudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='escudo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='img/escudos'),
        ),
    ]
