# Generated by Django 4.1.5 on 2023-01-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infomun', '0016_alter_municipio_escudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='docs'),
        ),
    ]
